version: "3.7"

networks:
  mern-local:

services:
  mern-api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: mern-api
    working_dir: /home/node/app
    entrypoint: "npm run live"
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - ~/.aws:/root/.aws
      - ./api:/home/node/app
    environment:
      - NODE_ENV=local
      - API_PORT=${API_PORT}
      - DEBUG=${DEBUG}
      - DEBUG_HIDE_DATE=${DEBUG_HIDE_DATE}
      - DEBUG_COLORS=${DEBUG_HIDE_DATE}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - MONGODB_URL=${MONGODB_URL}
    networks:
      mern-local:

  mern-mongodb:
    image: mongo
    container_name: mern-mongodb
    restart: unless-stopped
    volumes:
      - ./data/mongodb:/data/db
    ports:
      - ${MONGODB_PORT}:27017
    command: mongod --noauth
    networks:
      mern-local:

  mern-nginx:
    image: nginx:1.15-alpine
    container_name: mern-nginx
    restart: unless-stopped
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - ./client/build:/usr/share/nginx/html
    ports:
      - 80:80
      - 443:443
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''